<a href="https://colab.research.google.com/github/mauricionoronha/classificador_generico_simplificado/blob/main/classificador_generico_simplificado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <font color='#FFA500'> ETAPA 1 : Pré-processamento dos dados:</font>

* É o processo de limpar, transformar e preparar os dados brutos antes de serem alimentados para um modelo de aprendizado de máquina. 

* É uma etapa crucial em qualquer projeto de machine learning, pois a qualidade dos dados usados para treinar um modelo tem um grande impacto no desempenho e na precisão do modelo.

>Considerada a etapa mais demorada e trabalhosa, mas neste projeto será otimizado em 10 passos. Basta preencher as informações necessárias e rodar a célula.


## <font color='#FFA500'> 1/10 - Carregando a base de dados:</font>

In [ ]:
#@markdown ---

import pandas as pd
import numpy as np

print('Carregando dados...')
# Criação dos campos de preenchimento usando #@param
#@markdown > ### Insira o endereço do arquivo abaixo e escolha o tipo correto de arquivo que deseja importar:
endereco = "/content/drive/MyDrive/MACHINE_LEARNNING/telecom_users.xlsx" #@param {type:"string"}
tipo_arquivo = "excel" #@param ["csv", "excel"]
separador = ";" #@param [",", ";"]

if tipo_arquivo == "csv":
    dados = pd.read_csv( endereco, sep = separador)
else:
    dados = pd.read_excel(endereco)

print('Pronto, verifique as 5 primeiras linhas do dataframe:')
dados.head()



## <font color='#FFA500'> 2/10 - Analisando atributos ( variáveis )</font>

In [ ]:
#@markdown ---
#@markdown  ### Análise quantitativa em % e visualização gráfica por meio de um histograma.
#@markdown 
#@markdown > Informe o nome do atributo que deseja analisar:
import plotly.express as px
Nome_Atributo = "Churn" #@param {type:"string"}

print('Criando gráfico...')
print(display(dados[Nome_Atributo].value_counts(normalize=True).map("{:.1%}".format)));

hist1 =  px.histogram (dados,  x = Nome_Atributo, nbins=60) 
hist1.update_layout(width=800,height=500,title_text='Distribuição {}'.format(Nome_Atributo)) 
hist1.show()

dados2 = dados.copy()
print('Pronto')

## <font color='#FFA500'> 3/10 - Verificando e corrigindo valores nulos ( NAN )</font>

In [ ]:
#@markdown ---
print('Verificando dados...')
#@markdown > ### Rode essa célula para identificar valores nulos
print('\033[0m' + str(dados2.isnull().sum()))
print('\033[1;32mPronto')

In [ ]:
#@markdown > ### Se encontado valores nulos, como proceder?

#@markdown 1 - Excluir Dados Nulos

#@markdown 2 - Substituir Dados Nulos Pela Média

Escolha = 1 #@param ["1", "2"] {type:"raw"}

#@markdown > ###  Informe o nome do Atributo com dados nulos:

Nome_Atrib_Dados_Nulos = "Churn" #@param {type:"string"}


if Escolha == 1:
    dados2.dropna(inplace=True)
else:
    dados2[Nome_Atrib_Dados_Nulos].fillna(dados2[Nome_Atrib_Dados_Nulos].mean(), inplace=True)

print('Dados corrigidos!')



## <font color='#FFA500'>  4/10 - Analisando os tipos de atributos</font>

In [ ]:
#@markdown ---
#@markdown  ### Verifique os tipos de atributos, que podem ser:
#@markdown * object: strings
#@markdown * int64: inteiros
#@markdown * float64: reais
#@markdown * complex: complexos
print('Analisando dados...')
print('\033[0m' + str(dados2.dtypes))
print('Pronto')

In [ ]:
#@markdown > ### Será necessário alterar o tipo de um atributo especifico?

#@markdown * Desconsidere se não for necessário corrigir o tipo do atributo
print('Corrigindo dados...')
#@markdown > Se for necessário fazer a correção, informe o nome do atributo:
Nome_Atributo = "" #@param {type:"string"}
#@markdown > Escolha agora, entre as opções abaixo, para qual tipo deseja alterar:
Tipo_Atributo = "float64" #@param ["object", "int64", "float64"]

if Tipo_Atributo == "object":
    dados2[Nome_Atributo] = dados2[Nome_Atributo].astype(str)
elif Tipo_Atributo == "int64":
    dados2[Nome_Atributo] = dados2[Nome_Atributo].apply(np.int64)
else:
    dados2[Nome_Atributo] = dados2[Nome_Atributo].apply(np.float64)

print(dados2[Nome_Atributo].dtype)

#@markdown * OBS.: Só é possivel converter uma STRING (object) em INT ou FLOAT quando essa string é composta apenas por números, logo não é possivel converter palavras em int ou float
print('Pronto')


## <font color='#FFA500'> 5/10 - Excluindo atributos desnecessários</font>

In [ ]:
#@markdown ---
#@markdown > ### Informe o nome do atributo que deseja retirar do dataframe:
Nome_Atributo = "ValorBackupOnline" #@param {type:"string"}
dados2 = dados2.drop(Nome_Atributo, axis=1)
print('\033[1;32mAtributo excluído!')
print('\033[1;32mSegue amostra do dataframe atualizado:')
dados2.head()

## <font color='#FFA500'> 6/10 - Relação quantitativa entre todos os atributos e um atributo chave:</font>

In [ ]:
#@markdown ---
#@markdown * ### Veja através de histograma como o atributo chave é distribuído nos demais atributos do dataframe.
print('Criando gráficos...')
#@markdown > Informe o nome do atributo chave: 
import plotly.express as px

Atributo_Chave = "" #@param{type: 'string'}

for coluna in dados2:      
        fig = px.histogram(dados2, x=coluna,nbins=60, color=Atributo_Chave)
        fig.show()

print('Pronto')

## <font color='#FFA500'> 7/10 - Análise Estatística Descritiva</font>

In [ ]:
#@markdown ---

#@markdown > ### Tenha acesso aos seguintes perâmetros :

#@markdown * count: número de valores não nulos na coluna
#@markdown * mean: média dos valores na coluna
#@markdown * std: desvio padrão dos valores na coluna
#@markdown * 25%: primeiro quartil (valor abaixo do qual estão 25% dos valores)
#@markdown * 50%: segundo quartil, que é equivalente à mediana (valor abaixo do qual estão 50% dos valores)
#@markdown * 75%: terceiro quartil (valor abaixo do qual estão 75% dos valores)
#@markdown * max: valor máximo na coluna
print('Analisando dados...')
dados2.describe()




## <font color='#FFA500'> 8/10 - Verificando correlação entre variáveis</font>

In [ ]:
#@markdown ---
#@markdown > ### Rode a célula para verificar em um quadro com gráficos de dispersão se existe alguma correlação entre variáveis
print('Processando dados...')
import seaborn as sns
import matplotlib.pyplot as plt
sns.pairplot(dados2);

print('Criando gráficos...')

## <font color='#FFA500'> 9/10 - Verificando Outliers</font>

In [ ]:
#@markdown ---
#@markdown > ### Informe o nome do atributo para criar um gráfico Boxplot e identificar possíveis outliers ( discrepâncias ):
print('Criando gráfico...')
Nome_Atributo = "ValorMensal" #@param {type:"string"}

import plotly.express as px
px.box ( dados2, y = Nome_Atributo)

#@markdown * Apropriado para atributos categóricos ordinais ( que tenham valores numéricos )


In [ ]:
#@markdown ### Corrigindo outliers
#@markdown ---
#@markdown > ###  Informe o atributo para correção:
Nome_Atributo = "ValorTelefone" #@param {type:"string"}

#@markdown >###  Informe como tratar outliers:
#@markdown * 1 - Exclua valores discrepantes baseados um uma condição
#@markdown * 2 - Substitua valores discrepantes pela média baseado em uma condição
#@markdown * 3 - Substitua valores discrepantes por um valor específico baseado em uma condição
Tipo_correcao = "2" #@param ["1", "2", "3"]

#@markdown > ###  Informe agora qual a condição:
#@markdown Corrija todos os valores que sejam:
Tipo_condicao = "maior_que" #@param ["igual_a", "maior_que", "menor_que", "diferente_de"]
Valor = 0 #@param {type:"number"}

#@markdown ---
#@markdown > Se escolheu a opção 3 para substituir os valores discrepantes por um valor específico, informe o valor para qual deseja substituir:
Valor_substituição = 0 #@param {type:"number"}

if Tipo_correcao == 1:
    # excluir os dados de um atributo baseado em uma condição
    if Tipo_condicao == "igual_a":
        dados2 = dados2.drop(dados2[dados2[Nome_Atributo] == Valor].index, inplace = True)
    elif Tipo_condicao == "maior_que":
        dados2 = dados2.drop(dados2[dados2[Nome_Atributo] > Valor].index, inplace = True)
    elif Tipo_condicao == "menor_que":
        dados2 = dados2.drop(dados2[dados2[Nome_Atributo] < Valor].index, inplace = True)
    elif Tipo_condicao == "diferente_de":
        dados2 = dados2.drop(dados2[dados2[Nome_Atributo] != Valor].index, inplace = True)
elif Tipo_correcao == 2:
    # substituir os dados de um atributo pela média baseado em uma condição
    if Tipo_condicao == "igual_a":
        dados2.loc[dados2[Nome_Atributo] == Valor, Nome_Atributo] = dados2[Nome_Atributo].mean()
    elif Tipo_condicao == "maior_que":
        dados2.loc[dados2[Nome_Atributo] > Valor, Nome_Atributo] = dados2[Nome_Atributo].mean()
    elif Tipo_condicao == "menor_que":
        dados2.loc[dados2[Nome_Atributo] < Valor, Nome_Atributo] = dados2[Nome_Atributo].mean()
    elif Tipo_condicao == "diferente_de":
        dados2.loc[dados2[Nome_Atributo] != Valor, Nome_Atributo] = dados2[Nome_Atributo].mean()
else:
    # substituir os dados de um atributo por um valor específico baseado em uma condição
    if Tipo_condicao == "igual_a":
        dados2.loc[dados2[Nome_Atributo] == Valor, Nome_Atributo] = Valor_substituição
    elif Tipo_condicao == "maior_que":
        dados2.loc[dados2[Nome_Atributo] > Valor, Nome_Atributo] = Valor_substituição
    elif Tipo_condicao == "menor_que":
        dados2.loc[dados2[Nome_Atributo] < Valor, Nome_Atributo] = Valor_substituição
    elif Tipo_condicao == "diferente_de":
        dados2.loc[dados2[Nome_Atributo] != Valor, Nome_Atributo] = Valor_substituição

print('Dados corrigidos!')

## <font color='#FFA500'> 10/10 Salvando ou Carregando a base de dados pré-processada</font>

In [ ]:
#@markdown ---
#@markdown * ### Opcionalmente é possivel salvar o dataframe tratado como um arquivo csv para consultas posteriores e também é possível carregar um dataframe salvo 

import pandas as pd
import numpy as np

#@markdown >  Se deseja salvar o dataframe tratado, marque a caixa abaixo e informe o nome do arquivo:
Salvar = False #@param {type:"boolean"}
Nome_arquivo = "churn_TRATADO" #@param {type:"string"}
Nome_arquivo_csv = Nome_arquivo + ".csv"

if Salvar:
  dados2.to_csv(Nome_arquivo_csv,sep = ",", encoding = "utf-8",  index = False)
  print('Dados Salvos!')

#@markdown >  Se deseja carregar um dataframe tratado, marque a caixa abaixo e informe o endereço do arquivo e o separador:
Carregar = True #@param {type:"boolean"}
endereco = "/content/drive/MyDrive/MACHINE_LEARNNING/churn_TRATADO.csv" #@param {type:"string"}
separador = "," #@param [",", ";"]

if Carregar:
    dados2 = pd.read_csv(endereco, sep = separador, encoding = "utf-8")
    print('Pronto, Dataframe carregado!'),
    print('\033[0m' + str(""))
    print('\033[0m' + str(dados2.info()))







# <font color='#FFA500'>  ETAPA 2: Otimização dos dados para a criação do modelo</font>

In [2]:
#@markdown > ## <font color='#FFA500'> Transformando variáveis categóricas NOMINAIS em variáveis categóricas ORDINAIS </font>

#@markdown ---
#@markdown * ### É extremamente importante assegurar que não existam dados nominais (string) no dataframe, pois os modelos de machine learning usados entendem apenas dados numéricos (int ou float)

#@markdown * Essa tranformação ocorre do seguinte modo:

#@markdown * Considere um atributo Sexo com 2 opções: Masculino e Feminino. 

#@markdown * Realizando a transformação, os dados nominais "Masculino" e "Feminino" serão substituídos por dados ordinais 0 e 1. 

#@markdown  > ###  >>> Rode a célula para realizar os ajustes <<<

# Armazenando os indices das variaveis nominais para uso posterior ( onehotencoder )
indice_nominal = [dados2.columns.get_loc(col) for col in dados2.select_dtypes(include=[object]).columns]

# Importação da biblioteca para transformar as variáveis
from sklearn.preprocessing import LabelEncoder

# Criando uma lista com todos os atributos nominais
nominais = [i for i, dtype in enumerate(dados2.dtypes) if dtype == object]

# Usando LabelEncoder para transformar todos atributos nominais lista em ordinais 
for i in nominais:
    dados2.iloc[:, i] = LabelEncoder().fit_transform(dados2.iloc[:, i])

print('Dados alterados!')
print('\033[1;32mSegue amostra do dataframe atualizado:')
dados2.head()

Dados alterados!
Segue amostra do dataframe atualizado:


Genero  Dependentes  MesesComoCliente  ServicoTelefone  ValorTelefone  \
0       0            1                 9                1           54.9   
1       1            0                 9                1           54.9   
2       1            0                 4                1           54.9   
3       1            0                13                1           54.9   
4       0            0                 3                1           54.9   

   MultiplasLinhas  ServicoInternet  ValorInternet  ServicoSegurancaOnline  \
0                0                0           94.9                       0   
1                2                0           94.9                       0   
2                0                1          129.9                       0   
3                0                1          129.9                       0   
4                0                1          129.9                       0   

   ServicoBackupOnline  ProtecaoEquipamento  ServicoSuporteTecnico  \
0                    2                    0                      2   
1                    0                    0                      0   
2                    0                    2                      0   
3                    2                    2                      0   
4                    0                    0                      2   

   ServicoStreamingTV  ServicoFilmes  TipoContrato  FaturaDigital  \
0                   2              0             1              1   
1                   0              2             2              0   
2                   0              0             2              1   
3                   2              2             2              1   
4                   2              0             2              1   

   FormaPagamento  ValorMensal  Churn  
0               1        199.6      0  
1               1        169.7      0  
2               0        184.8      1  
3               0        254.5      1  
4               1        224.7      1

In [3]:
#@markdown > ## <font color='#FFA500'> Divisão de Previsores e Alvo </font>
#@markdown ---
#@markdown * Atributos Previsores - (também conhecidos como "features" ou "variáveis independentes") são as características ou variáveis de entrada que são utilizadas para prever o valor de uma variável de saída. Em outras palavras, os atributos previsores são as informações que alimentam um modelo de machine learning, com o objetivo de produzir uma previsão ou classificação.
#@markdown * Atributo Alvo (também conhecido como "variável dependente" ou "rótulo") é a variável de saída que o modelo de machine learning está tentando prever ou classificar com base nos atributos previsores.

#@markdown > ### Informe o Atributo Alvo do dataframe:
Nome_Atributo = "Churn" #@param {type:"string"}
# o complemento .values retorna uma matriz com os dados do dataframe
# Divisão previsores e alvo
previsores = dados2.drop(Nome_Atributo, axis=1).values
alvo = dados2[[Nome_Atributo]].values

# Excluindo o atributo Alvo da lista de indice_nominal
indice_alvo = dados2.columns.get_loc(Nome_Atributo)
indice_nominal.remove(indice_alvo)
print('Previsores e Alvo criados!')

Previsores e Alvo criados!


In [4]:
#@markdown > ## <font color='#FFA500'> Escalonamento de variáveis </font>
#@markdown ---
#@markdown * O objetivo do escalonamento de variáveis é normalizar as variáveis para que elas tenham a mesma escala e variem em uma faixa semelhante.

#@markdown * Isso é necessário porque muitos algoritmos de Machine Learning são sensíveis à escala das variáveis. Se as variáveis tiverem escalas muito diferentes, isso pode levar a problemas como o algoritmo atribuir maior importância a variáveis com escalas maiores e menor importância a variáveis com escalas menores. Além disso, pode afetar a convergência dos algoritmos.

#@markdown  > ###  >>> Rode a célula para realizar os ajustes <<<

# Importanto as bibliotecas necessárias:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

previsores_one = ColumnTransformer(transformers = [("OneHot", OneHotEncoder(), indice_nominal)],
                                       remainder = "passthrough").fit_transform(previsores)

previsores_esc = StandardScaler().fit_transform(previsores_one)                                       
print('Escalonamento efetuado!')
print('Segue os dados escalonados:')
previsores_esc


Escalonamento efetuado!
Segue os dados escalonados:


array([[ 1.01923578, -1.01923578, -1.5306916 , ..., -0.65455138,
        -0.31864502, -0.39402955],
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.65455138,
        -0.31864502, -0.59847607],
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.65455138,
         0.01691246, -0.49522716],
       ...,
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.80079527,
         0.20865958, -0.29078064],
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.80079527,
        -0.31864502, -0.7352296 ],
       [-0.98112726,  0.98112726, -1.5306916 , ..., -0.80079527,
        -0.31864502, -0.59915984]])

In [5]:
#@markdown  ## <font color='#FFA500'> Separando base de treino e teste </font>
#@markdown ---
#@markdown * Informe o tamanho em porcentagem dos dados de teste. O restante será separado automaticamente para dos dados de treino. 

1#@markdown > O tamanho padrão de dados de teste é de 30% mas você pode escolher outros tamanhos conforme a necessidade: 
Tamanho_Base_Teste = "30% - PADRAO" #@param ["10%", "15%", "20%", "25%", "30% - PADRAO", "35%", "40%", "45%", "50%"]
if Tamanho_Base_Teste == "20%":
    Tamanho_Teste = 0.2
elif Tamanho_Base_Teste == "25%":
    Tamanho_Teste = 0.25
elif Tamanho_Base_Teste == "30% - PADRAO":
    Tamanho_Teste = 0.3
elif Tamanho_Base_Teste == "35%":
    Tamanho_Teste = 0.35
elif Tamanho_Base_Teste == "40%":
    Tamanho_Teste = 0.4
elif Tamanho_Base_Teste == "45%":
    Tamanho_Teste = 0.45
elif Tamanho_Base_Teste == "50%":
    Tamanho_Teste = 0.5
else:
    print("Valor inválido para Tamanho_Base_Teste")

# Importação de biblioteca 
from sklearn.model_selection import train_test_split

# Divisão de dados de treino e teste:
x_treino,x_teste,y_treino,y_teste = train_test_split(previsores_esc, alvo, test_size=Tamanho_Teste, random_state=0)

print('\033[1;32mDivisão efetuada!')
print('\033[1;32mTamanho base de treino (linhas, colunas):')
print('\033[0m'+ str(x_treino.shape))
print('\033[1;32mTamanho base de teste (linhas, colunas):')
print('\033[0m'+ str(x_teste.shape))

Divisão efetuada!
Tamanho base de treino (linhas, colunas):
(4188, 43)
Tamanho base de teste (linhas, colunas):
(1796, 43)


# <font color='#FFA500'> ETAPA 3: Aplicação dos algoritmos de Machine Leaning</font>

Neste projeto será utilizado os principais algoritmos de classificação para aprendizado supervisionado, sendo eles:
* Naive Bayes
* SVM (Máquina de Vetor de Suporte)
* Regressão Logística
* KNN (K Vizinhos Próximos)
* Árvore de Decisão
* Random Forest
* XGBoost
* Light GBM


Alguns algoritmos disponibilizam configuração de hiperparâmetros para otimização de resultados. 

> ## ATENÇÃO!!! 
É possível rodar todos os algoritmos de uma única vez minimizando as células seguintes com a seta ao lado.
Todos os hiperparâmetros já estão estão configurados como default.


### <font color='#FFFF00'> Naive Bayes</font>

In [6]:
#@markdown ---
#@markdown Naive Bayes é um método probabilístico utilizado para classificar dados em categorias. Ele utiliza o Teorema de Bayes para calcular a probabilidade de um dado pertencer a uma determinada categoria com base nas probabilidades condicionais dos atributos que o caracterizam.
#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada
print('\033[1;32mProcessando Naive Bayes...')
print('\033[0m'+ str(55*"="))


# Importando as biliotecas:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Treinando o algoritmo:
naive = GaussianNB()
naive.fit(x_treino,y_treino)

# Usando base de teste
previsoes_naive = naive.predict(x_teste)

# Usando base de treino
previsoes_treino = naive.predict(x_treino)

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste, previsoes_naive)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))

print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste,previsoes_naive)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste,previsoes_naive)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

# Importando as bibliotecas para Validação Cruzada
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

# Criando o modelo
modelo_nbayes = GaussianNB()
resultado_nbayes = cross_val_score(modelo_nbayes,previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão
print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_nbayes.mean()*100)))
print("")
print(55*"=")
print("")

print('\033[1;32mNaive Bayes finalizado!')

Processando Naive Bayes...

Acurácia da Base de Teste:
68.26%

Acurácia da Base de Treino:
69.15%


Matriz de Confusão da Base de Teste:
[[842 498]
 [ 72 384]]

Matriz de Confusão da Base de Treino:
[[1924 1133]
 [ 159  972]]


Relatório de Classificação da Base de Teste:
              precision    recall  f1-score   support

           0       0.92      0.63      0.75      1340
           1       0.44      0.84      0.57       456

    accuracy                           0.68      1796
   macro avg       0.68      0.74      0.66      1796
weighted avg       0.80      0.68      0.70      1796

Relatório de Classificação da Base de Treino:
              precision    recall  f1-score   support

           0       0.92      0.63      0.75      3057
           1       0.46      0.86      0.60      1131

    accuracy                           0.69      4188
   macro avg       0.69      0.74      0.67      4188
weighted avg       0.80      0.69      0.71      4188



Acurácia na Validação Cru

### <font color='#FFFF00'> SVM - Máquina de Vetor de Suporte</font>

In [7]:
#@markdown ---
#@markdown O SVM (Support Vector Machine)  pode ser usado para problemas de classificação e regressão. O objetivo do SVM é encontrar um hiperplano que separe os dados em diferentes classes, maximizando a margem entre os pontos mais próximos de cada classe.

#@markdown ### Hiperparâmetros:
#@markdown > * C: Parâmetro de regularização. Um valor mais alto de C implica em uma classificação mais precisa dos dados de treinamento, mas pode resultar em sobreajuste.
#@markdown >
#@markdown > #### Informe o valor de C :
Valor_C = 60 #@param {type:"slider", min:0, max:100, step:1}
#@markdown >
#@markdown > * Kernel: utilizado para mapear os dados de entrada em um espaço de características de maior dimensão. Os kernels comuns são:
#@markdown >> * Linear: adequado para problemas de classificação simples onde os dados podem ser linearmente separáveis.
#@markdown >> * Polinomial: capaz de separar dados que não são linearmente separáveis, mas pode ser suscetível ao overfitting.
#@markdown >> * RBF (Função de Base Radial): capaz de separar dados que não são linearmente separáveis e geralmente produz resultados melhores que o kernel polinomial.
#@markdown >> * Sigmoid: adequado para problemas de classificação binária e é especialmente útil para problemas em que os dados têm uma distribuição bimodal.
#@markdown >  #### Informe o Kernel:
Tipo_Kernel = "sigmoid" #@param ["linear", "polynomial", "rbf", "sigmoid"]

#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada

print('\033[1;32mProcessando SVM...')
print('\033[0m'+ str(55*"="))

# Importando a biblioteca SVM especifico para classificação ( SVC )
from sklearn.svm import SVC   
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Cria o vetor "svm". A configuração kernel para transformar os dados para aplicação da forma correta
svm = SVC(kernel=Tipo_Kernel, random_state=1, C= Valor_C) 

# Criação do fit de treinamento
svm.fit(x_treino, y_treino)

# Criação do PREVISOR baseado no svm
svm_teste =svm.predict(x_teste)

# Criação do PREVISOR da base de treino
svm_treino = svm.predict(x_treino)

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste, svm_teste)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino, svm_treino)*100))


print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste, svm_teste)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino, svm_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste, svm_teste)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino,svm_treino)))

print("")
print(55*"=")
print("")

# Validação cruzada:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

#Criando o modelo
modelo_svm=SVC(kernel= Tipo_Kernel,random_state=1,C= Valor_C)
resultado_svm= cross_val_score(modelo_svm, previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão
print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_svm.mean()*100)))

print("")
print(55*"=")
print("")

print('\033[1;32mSVM finalizado!')


Processando SVM...

Acurácia da Base de Teste:
73.39%

Acurácia da Base de Treino:
72.71%


Matriz de Confusão da Base de Teste:
[[1095  245]
 [ 233  223]]

Matriz de Confusão da Base de Treino:
[[2487  570]
 [ 573  558]]


Relatório de Classificação da Base de Teste:
              precision    recall  f1-score   support

           0       0.82      0.82      0.82      1340
           1       0.48      0.49      0.48       456

    accuracy                           0.73      1796
   macro avg       0.65      0.65      0.65      1796
weighted avg       0.74      0.73      0.73      1796

Relatório de Classificação da Base de Treino:
              precision    recall  f1-score   support

           0       0.81      0.81      0.81      3057
           1       0.49      0.49      0.49      1131

    accuracy                           0.73      4188
   macro avg       0.65      0.65      0.65      4188
weighted avg       0.73      0.73      0.73      4188



Acurácia na Validação Cruzada

### <font color='#FFFF00'> Regressão Logística</font>

In [8]:
#@markdown A Regressão Logística é um algoritmo de aprendizado de máquina utilizado para classificação binária, ou seja, para prever se uma observação pertence a uma das duas categorias possíveis (por exemplo, sim ou não, verdadeiro ou falso, etc.).

#@markdown ### Hiperparâmetros:
#@markdown ---

#@markdown ### Max_Iter:
#@markdown  Define o número máximo de iterações para o algoritmo convergir. Este parâmetro controla a quantidade de tempo que o modelo terá para encontrar o melhor conjunto de pesos.
#@markdown >
#@markdown >  #### Informe o valor de Max_Iter :
Valor_Max_Iter = 500 #@param {type:"slider", min:20, max:1000, step:20}
#@markdown ---

#@markdown ### Penalty:
#@markdown  Define o tipo de regularização que será aplicada ao modelo. A regularização é uma técnica que ajuda a prevenir overfitting, penalizando coeficientes muito grandes. Opções:
#@markdown * l1: Adiciona uma penalidade igual à soma dos valores absolutos dos coeficientes. Essa opção pode ser usada para selecionar recursos importantes do modelo, tornando os outros coeficientes iguais a zero.
#@markdown * l2: Regularização L2: Adiciona uma penalidade igual à soma dos quadrados dos coeficientes. Essa opção pode ser usada para evitar overfitting, tornando os coeficientes pequenos, mas não necessariamente iguais a zero.
#@markdown >  #### Informe o Penalty:
Tipo_Penalty = "l2" #@param ["l1", "l2"]
#@markdown ---

#@markdown ### C:
#@markdown  Define o inverso da força da regularização. Quanto maior o valor de C, menos regularização é aplicada. Este parâmetro pode ser usado para controlar o trade-off entre o viés e a variância do modelo.
#@markdown > #### Informe o valor de C:
Valor_C = 4 #@param {type:"slider", min:1, max:10, step:1}
#@markdown ---

#@markdown ### Solver:
#@markdown  Define o algoritmo a ser utilizado no processo de otimização. Opções:
#@markdown * newton-cg: É eficiente para dados com muitas amostras e muitas características, mas pode ser lento para conjuntos de dados muito grandes. <font color='#FFFF00'> Somente para Penalty l2 </font>
#@markdown * lbfgs: É uma opção mais rápida que o solver "newton-cg" e é adequado para conjuntos de dados com muitas amostras e poucas características. <font color='#FFFF00'> Somente para Penalty l2 </font>
#@markdown * liblinear: É uma opção mais rápida para conjuntos de dados pequenos e médios, mas pode ter dificuldades para convergir em conjuntos de dados muito grandes.
#@markdown * saga: É adequado para conjuntos de dados grandes, mas pode ter dificuldades para convergir em problemas com regularização L1.

#@markdown >  #### Informe o Solver:
Tipo_Solver = "lbfgs" #@param ["newton-cg", "lbfgs", "liblinear", "saga"]
#@markdown ---

#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada

print('\033[1;32mProcessando Regressão Logística...')
print('\033[0m'+ str(55*"="))

# Importando biblioteca LogisticRegression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Criando o modelo
logistica = LogisticRegression(random_state=1,max_iter= Valor_Max_Iter, penalty= Tipo_Penalty,tol=0.0001, C= Valor_C, solver= Tipo_Solver)

# Criação do fit de treinamento
logistica.fit(x_treino,y_treino)

# Criação do PREVISOR da base de teste
previsoes_logistica = logistica.predict(x_teste)

# Criando Dataframe para receber dados treino
previsoes_treino= logistica.predict(x_treino)

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste,previsoes_logistica)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))

print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste, previsoes_logistica)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino, previsoes_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste, previsoes_logistica)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

# Validação cruzada:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

#Criando o modelo
#Criando o modelo
modelo_rl=LogisticRegression(random_state=1,max_iter= Valor_Max_Iter, penalty= Tipo_Penalty,tol=0.0001, C= Valor_C, solver= Tipo_Solver)
resultado_rl= cross_val_score(modelo_rl, previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão
print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_rl.mean()*100)))

print("")
print(55*"=")
print("")

print('\033[1;32mRegressão Logística finalizada!')

Processando Regressão Logística...

Acurácia da Base de Teste:
78.79%

Acurácia da Base de Treino:
80.44%


Matriz de Confusão da Base de Teste:
[[1182  158]
 [ 223  233]]

Matriz de Confusão da Base de Treino:
[[2749  308]
 [ 511  620]]


Relatório de Classificação da Base de Teste:
              precision    recall  f1-score   support

           0       0.84      0.88      0.86      1340
           1       0.60      0.51      0.55       456

    accuracy                           0.79      1796
   macro avg       0.72      0.70      0.71      1796
weighted avg       0.78      0.79      0.78      1796

Relatório de Classificação da Base de Treino:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      3057
           1       0.67      0.55      0.60      1131

    accuracy                           0.80      4188
   macro avg       0.76      0.72      0.74      4188
weighted avg       0.80      0.80      0.80      4188



Acurácia na V

### <font color='#FFFF00'> KNN</font>

In [9]:
#@markdown O objetivo do KNN é classificar uma amostra desconhecida com base nas classes de exemplos de treinamento mais próximos. Isso é feito calculando a distância entre a amostra desconhecida e todos os exemplos de treinamento no espaço de recursos e selecionando os k exemplos de treinamento mais próximos. A classe mais comum entre esses k exemplos é então atribuída à amostra desconhecida.
#@markdown ### Hiperparâmetros:
#@markdown ---

#@markdown ### N_Neighbors:
#@markdown  é um dos principais parâmetros do algoritmo KNN (K-Nearest Neighbors). Ele controla o número de vizinhos mais próximos que serão considerados para determinar a classe de uma nova amostra. Em outras palavras, o valor de n_neighbors define o tamanho do subconjunto de amostras de treinamento que serão usadas para tomar uma decisão sobre a classe de uma nova amostra.
#@markdown >
#@markdown >  #### Informe o valor de N_Neighbors :
Valor_N_Neighbors = 30 #@param {type:"slider", min:1, max:30, step:1}
#@markdown ---

#@markdown ### Metric:
#@markdown  Metric controla a métrica de distância que será utilizada para medir a distância entre as amostras do conjunto de treinamento e a nova amostra a ser classificada. Opções:
#@markdown * euclidean: mede a distância entre dois pontos em um espaço euclidiano, definida pela raiz quadrada da soma dos quadrados das diferenças entre as coordenadas dos dois pontos.
#@markdown * manhattan: mede a distância entre dois pontos ao longo dos eixos, em vez de uma linha reta. A distância Manhattan é definida pela soma das diferenças absolutas entre as coordenadas dos dois pontos.
#@markdown * chebyshev: mede a distância máxima ao longo de qualquer dimensão entre dois pontos. É definida como o valor absoluto da diferença máxima entre as coordenadas dos dois pontos.
#@markdown * minkowski: é uma métrica de distância geral que inclui a distância Euclidiana e a distância de Manhattan como casos especiais. 
#@markdown * cosine: calcula a similaridade entre duas amostras, em vez da distância. É útil para dados esparsos e para dados onde a magnitude das características é irrelevante.

#@markdown >  #### Informe o Metric:
Tipo_Metric = "cosine" #@param ["euclidean", "manhattan", "chebyshev", "minkowski", "cosine"]
#@markdown ---


#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada

print('\033[1;32mProcessando KNN...')
print('\033[0m'+ str(55*"="))

# Importando biblioteca 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Criando o modelo. Se metrics for minkowski recebe um componente adicional p
if Tipo_Metric == 'minkowski':
    knn = KNeighborsClassifier(n_neighbors=Valor_N_Neighbors, metric='minkowski',p=2,)
else:
    knn = KNeighborsClassifier(n_neighbors=Valor_N_Neighbors, metric=Tipo_Metric)

# Criação do fit de treinamento
knn.fit(x_treino,y_treino)

# Criação do PREVISOR da base de teste
previsoes_knn = knn.predict(x_teste)

# Criando Dataframe para receber dados treino
previsoes_treino= knn.predict(x_treino)

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste, previsoes_knn)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))

print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste,previsoes_knn)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino, previsoes_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste,previsoes_knn)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

# Validação cruzada:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)


# Criando o modelo. Se metrics for minkowski recebe um componente adicional p
if Tipo_Metric == 'minkowski':
    modelo_knn= KNeighborsClassifier(n_neighbors=Valor_N_Neighbors, metric='minkowski',p=2,)
else:
    modelo_knn= KNeighborsClassifier(n_neighbors=Valor_N_Neighbors, metric=Tipo_Metric)

resultado_knn =cross_val_score(modelo_knn, previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão

print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_knn.mean()*100)))

print("")
print(55*"=")
print("")

print('\033[1;32mKNN finalizada!')

Processando KNN...

Acurácia da Base de Teste:
77.51%

Acurácia da Base de Treino:
79.85%


Matriz de Confusão da Base de Teste:
[[1159  181]
 [ 223  233]]

Matriz de Confusão da Base de Treino:
[[2711  346]
 [ 498  633]]


Relatório de Classificação da Base de Teste:
              precision    recall  f1-score   support

           0       0.84      0.86      0.85      1340
           1       0.56      0.51      0.54       456

    accuracy                           0.78      1796
   macro avg       0.70      0.69      0.69      1796
weighted avg       0.77      0.78      0.77      1796

Relatório de Classificação da Base de Treino:
              precision    recall  f1-score   support

           0       0.84      0.89      0.87      3057
           1       0.65      0.56      0.60      1131

    accuracy                           0.80      4188
   macro avg       0.75      0.72      0.73      4188
weighted avg       0.79      0.80      0.79      4188



Acurácia na Validação Cruzada

### <font color='#FFFF00'> Árvore de Decisão</font>

In [10]:
#@markdown Árvore de decisão é um modelo de aprendizado de máquina supervisionado que pode ser usado tanto para tarefas de classificação quanto de regressão. A árvore de decisão divide o conjunto de dados em subconjuntos menores, com base nos valores das variáveis ​​explicativas, para prever a variável de resposta.
#@markdown ### Hiperparâmetros:
#@markdown ---

#@markdown ### Criterion:
#@markdown  é usado na árvore de decisão para definir o critério de avaliação da qualidade da divisão em cada nó da árvore. Existem dois critérios populares usados na árvore de decisão:
#@markdown * gini: O critério de impureza de Gini mede a probabilidade de classificar incorretamente uma amostra aleatória com base na distribuição das classes naquele nó. Quanto menor o valor da impureza de Gini, mais puro é o nó em termos de distribuição de classe.
#@markdown * entropy: O critério de entropia mede a incerteza da classificação em um determinado nó. Ele é calculado como a soma ponderada do logaritmo da probabilidade de cada classe, multiplicado pela probabilidade negativa. Quanto menor o valor da entropia, mais puro é o nó em termos de distribuição de classe.
#@markdown >  #### Informe o valor de Criterion :
Tipo_Criterion = "entropy" #@param ["gini", "entropy"]
#@markdown ---

#@markdown ### Max_Depth:
#@markdown  hiperparâmetro importante na árvore de decisão que controla a profundidade máxima da árvore. A profundidade de uma árvore de decisão é medida pelo número de ramos que precisamos seguir a partir da raiz para chegar a um nó folha.

#@markdown Limitar a profundidade da árvore pode ajudar a evitar o sobreajuste (overfitting) do modelo. Isso significa que, ao limitar a profundidade máxima da árvore, estamos impedindo que a árvore se torne muito complexa e especializada no conjunto de treinamento específico.

#@markdown No entanto, definir um valor muito baixo para max_depth pode resultar em subajuste (underfitting), onde o modelo não é complexo o suficiente para capturar padrões importantes no conjunto de dados.

#@markdown >  #### Informe o valor de Max_Depth:
Valor_Max_Depth = 4 #@param {type:"slider", min:1, max:10, step:1}
#@markdown ---


#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada

print('\033[1;32mProcessando Árvore de Decisão...')
print('\033[0m'+ str(55*"="))

# Importando biblioteca 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Criando o modelo. 
arvore = DecisionTreeClassifier(criterion= Tipo_Criterion,random_state=0,max_depth= Valor_Max_Depth)

# Criação do fit de treinamento
arvore.fit(x_treino,y_treino)

# Criação do PREVISOR da base de teste
previsoes_arvore = arvore.predict(x_teste)

# Criando Dataframe para receber dados treino
previsoes_treino = arvore.predict(x_treino)

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste,previsoes_arvore)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))

print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste,previsoes_arvore)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste,previsoes_arvore)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

# Validação cruzada:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

# Criando o modelo.
modelo_ad =DecisionTreeClassifier(criterion= Tipo_Criterion,random_state=0,max_depth= Valor_Max_Depth)

resultado_ad =cross_val_score(modelo_ad, previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão
print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_ad.mean()*100)))

print("")
print(55*"=")
print("")

print('\033[1;32mÁrvore de Decisão Finalizada!')

Processando Árvore de Decisão...

Acurácia da Base de Teste:
78.34%

Acurácia da Base de Treino:
80.06%


Matriz de Confusão da Base de Teste:
[[1203  137]
 [ 252  204]]

Matriz de Confusão da Base de Treino:
[[2792  265]
 [ 570  561]]


Relatório de Classificação da Base de Teste:
              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1340
           1       0.60      0.45      0.51       456

    accuracy                           0.78      1796
   macro avg       0.71      0.67      0.69      1796
weighted avg       0.77      0.78      0.77      1796

Relatório de Classificação da Base de Treino:
              precision    recall  f1-score   support

           0       0.83      0.91      0.87      3057
           1       0.68      0.50      0.57      1131

    accuracy                           0.80      4188
   macro avg       0.75      0.70      0.72      4188
weighted avg       0.79      0.80      0.79      4188



Acurácia na Val

### <font color='#FFFF00'> Random Forest</font>


In [11]:
#@markdown É um algoritmo que combina várias árvores de decisão para fazer previsões. É altamente preciso e pode lidar com conjuntos de dados grandes com características de alta dimensão. Um aspecto importante do algoritmo Random Forest é a sua capacidade de evitar overfitting. 
#@markdown ### Hiperparâmetros:
#@markdown ---

#@markdown ### N_Estimators:
#@markdown  este é o número de árvores de decisão a serem construídas pelo algoritmo. Valores mais altos podem levar a um modelo mais preciso, mas também aumentam o risco de overfitting.
#@markdown >  #### Informe o valor de Max_Depth :
Valor_N_Estimators = 500 #@param {type:"slider", min:10, max:500, step:10}
#@markdown ---

#@markdown ### Criterion:
#@markdown  é usado na árvore de decisão para definir o critério de avaliação da qualidade da divisão em cada nó da árvore. Existem dois critérios populares usados na árvore de decisão:
#@markdown * gini: O critério de impureza de Gini mede a probabilidade de classificar incorretamente uma amostra aleatória com base na distribuição das classes naquele nó. Quanto menor o valor da impureza de Gini, mais puro é o nó em termos de distribuição de classe.
#@markdown * entropy: O critério de entropia mede a incerteza da classificação em um determinado nó. Ele é calculado como a soma ponderada do logaritmo da probabilidade de cada classe, multiplicado pela probabilidade negativa. Quanto menor o valor da entropia, mais puro é o nó em termos de distribuição de classe.
#@markdown >  #### Informe o valor de Criterion :
Tipo_Criterion = "entropy" #@param ["gini", "entropy"]
#@markdown ---

#@markdown ### Max_Depth:
#@markdown   é a profundidade máxima que cada árvore de decisão pode atingir. Árvores mais profundas podem capturar mais detalhes nos dados, mas também podem levar a overfitting.

#@markdown >  #### Informe o valor de Max_Depth:
Valor_Max_Depth = 7 #@param {type:"slider", min:1, max:10, step:1}
#@markdown ---



#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada

print('\033[1;32mProcessando Random Forest...')
print('\033[0m'+ str(55*"="))

# Importando biblioteca 
from sklearn.ensemble import RandomForestClassifier

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Criando o modelo. 
random = RandomForestClassifier(n_estimators= Valor_N_Estimators, criterion= Tipo_Criterion, random_state = 0, max_depth= Valor_Max_Depth)

# Criação do fit de treinamento
random.fit(x_treino, y_treino)

# Criação do PREVISOR da base de teste
previsoes_random = random.predict(x_teste)

# Criando Dataframe para receber dados treino
previsoes_treino = random.predict(x_treino)

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste, previsoes_random)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino, previsoes_treino)*100))

print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste, previsoes_random)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste, previsoes_random)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

# Validação cruzada:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

# Criando o modelo.
modelo_rf = RandomForestClassifier(n_estimators= Valor_N_Estimators, criterion= Tipo_Criterion, random_state = 0, max_depth= Valor_Max_Depth)

resultado_rf = cross_val_score(modelo_rf, previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão
print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_rf.mean()*100)))

print("")
print(55*"=")
print("")

print('\033[1;32mRandom Forest Finalizado!')

Processando Random Forest...

Acurácia da Base de Teste:
79.45%

Acurácia da Base de Treino:
82.09%


Matriz de Confusão da Base de Teste:
[[1210  130]
 [ 239  217]]

Matriz de Confusão da Base de Treino:
[[2829  228]
 [ 522  609]]


Relatório de Classificação da Base de Teste:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1340
           1       0.63      0.48      0.54       456

    accuracy                           0.79      1796
   macro avg       0.73      0.69      0.70      1796
weighted avg       0.78      0.79      0.78      1796

Relatório de Classificação da Base de Treino:
              precision    recall  f1-score   support

           0       0.84      0.93      0.88      3057
           1       0.73      0.54      0.62      1131

    accuracy                           0.82      4188
   macro avg       0.79      0.73      0.75      4188
weighted avg       0.81      0.82      0.81      4188



Acurácia na Validaç

### <font color='#FFFF00'> XGBOOST</font>

In [12]:
#@markdown Algoritmo de aprendizado de máquina baseado em árvores de decisão que foi desenvolvido para melhorar o desempenho do Gradient Boosting. O XGBoost funciona através da criação de um conjunto de árvores de decisão sequenciais, onde cada nova árvore é treinada para corrigir os erros do modelo anterior. Isso é conhecido como boosting, que é um método de aprendizado em que os modelos mais fracos são combinados para criar um modelo mais forte.
#@markdown ### Hiperparâmetros:
#@markdown ---

#@markdown ### Max_Depth:
#@markdown  a profundidade máxima de cada árvore. Valores mais altos podem levar a um modelo mais preciso, mas também aumentam o risco de overfitting.
#@markdown >  #### Informe o valor de Max_Depth :
Valor_Max_Depth = 2 #@param {type:"slider", min:1, max:10, step:1}
#@markdown ---

#@markdown ### Learning_Rate:
#@markdown  a taxa de aprendizado do modelo. Valores menores podem levar a uma melhor precisão do modelo, mas também aumentam o tempo de treinamento.

#@markdown >  #### Informe o valor de Learning_Rate:
Valor_Learning_Rate = 0.5 #@param {type:"slider", min:0.1, max:10, step:0.1}
#@markdown ---

#@markdown ### N_Estimators :
#@markdown  especifica o número de árvores de decisão que serão criadas no modelo. Cada árvore é adicionada sequencialmente ao modelo e visa corrigir os erros do modelo anterior. Um valor muito baixo pode resultar em um modelo impreciso, enquanto um valor muito alto pode resultar em overfitting e um modelo que não generaliza bem para novos dados.

#@markdown >  #### Informe o valor de N_Estimators:
Valor_N_Estimators = 50 #@param {type:"slider", min:10, max:500, step:10}
#@markdown ---

#@markdown ### Objective :
#@markdown  especifica a função objetivo a ser otimizada durante o treinamento do modelo. A escolha da função objetivo depende do tipo de problema que está sendo abordado, como regressão ou classificação binária/multiclasse. Opções:
#@markdown * reg:squarederror: Erro quadrático médio para problemas de regressão.
#@markdown * reg:logistic: Função de perda de regressão logística para problemas de classificação binária.
#@markdown * binary:logistic:  Função de perda de regressão logística para problemas de classificação binária.
#@markdown * multi:softmax: Função de perda de entropia cruzada para problemas de classificação multiclasse.
#@markdown * rank:pairwise: Função de perda de classificação para problemas de classificação de ranking.

#@markdown >  #### Informe o tipo de Objective:
Tipo_Objective = "reg:logistic" #@param ["reg:squarederror", "reg:logistic", "binary:logistic", "multi:softmax", "rank:pairwise"]
#@markdown ---

#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada

print('\033[1;32mProcessando XGBOOST...')
print('\033[0m'+ str(55*"="))

# Importando biblioteca 
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Criando o modelo. 
xg=XGBClassifier(max_depth= Valor_Max_Depth, learning_rate= Valor_Learning_Rate, n_estimators= Valor_N_Estimators, objective=Tipo_Objective, random_state=3)

# Criação do fit de treinamento
xg.fit(x_treino, y_treino)

# Criação do PREVISOR da base de teste
previsoes_xg = xg.predict(x_teste)

# Criando Dataframe para receber dados treino
previsoes_treino=xg.predict(x_treino)

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste,previsoes_xg)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))

print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste,previsoes_xg)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste,previsoes_xg)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino,previsoes_treino)))

print("")
print(55*"=")
print("")

# Validação cruzada:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

# Criando o modelo.
modelo_xgboost =XGBClassifier(max_depth= Valor_Max_Depth, learning_rate= Valor_Learning_Rate, n_estimators= Valor_N_Estimators, objective=Tipo_Objective, random_state=3)		

resultado_xgboost = cross_val_score(modelo_xgboost, previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão
print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_xgboost.mean()*100)))

print("")
print(55*"=")
print("")

print('\033[1;32mXGBOOST Finalizado!')

Processando XGBOOST...

Acurácia da Base de Teste:
79.84%

Acurácia da Base de Treino:
81.95%


Matriz de Confusão da Base de Teste:
[[1203  137]
 [ 225  231]]

Matriz de Confusão da Base de Treino:
[[2795  262]
 [ 494  637]]


Relatório de Classificação da Base de Teste:
              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1340
           1       0.63      0.51      0.56       456

    accuracy                           0.80      1796
   macro avg       0.74      0.70      0.71      1796
weighted avg       0.79      0.80      0.79      1796

Relatório de Classificação da Base de Treino:
              precision    recall  f1-score   support

           0       0.85      0.91      0.88      3057
           1       0.71      0.56      0.63      1131

    accuracy                           0.82      4188
   macro avg       0.78      0.74      0.75      4188
weighted avg       0.81      0.82      0.81      4188



Acurácia na Validação Cru

### <font color='#FFFF00'> LightGBM</font>

In [13]:
print('\033[1;32mProcessando LightGBM...')
print('\033[0m'+ str(55*"="))

#@markdown Algoritmo de aprendizado de máquina baseado em árvore que se destaca pela sua eficiência e escalabilidade. Ele usa uma técnica chamada "histograma de decisão" para construir as árvores de decisão, o que torna a construção das árvores muito mais rápida do que os algoritmos tradicionais de árvore de decisão.
#@markdown ### Hiperparâmetros:
#@markdown ---

#@markdown ### Num_Boost_Round :
#@markdown é um parâmetro no LightGBM, que especifica o número máximo de iterações de treinamento que serão realizadas para ajustar o modelo. Cada iteração adiciona uma nova árvore ao modelo, de modo que aumentar o número de iterações aumenta a complexidade do modelo.

#@markdown >  #### Informe o valor de Num_Boost_Round:
Valor_Num_Boost_Round = 20 #@param {type:"slider", min:10, max:500, step:10}
#@markdown ---


#@markdown ### Max_Depth:
#@markdown  este é o limite máximo de profundidade da árvore. Quanto mais profunda a árvore, mais complexa ela será e mais fácil será para o modelo memorizar os dados de treinamento. No entanto, um número muito grande de profundidade pode levar ao overfitting.
#@markdown >  #### Informe o valor de Max_Depth :
Valor_Max_Depth = 2 #@param {type:"slider", min:1, max:10, step:1}
#@markdown ---

#@markdown ### Learning_Rate:
#@markdown  a taxa de aprendizado do modelo. Valores menores podem levar a uma melhor precisão do modelo, mas também aumentam o tempo de treinamento.

#@markdown >  #### Informe o valor de Learning_Rate:
Valor_Learning_Rate = 0.2 #@param {type:"slider", min:0.1, max:10, step:0.1}
#@markdown ---

#@markdown ### Num_Leaves :
#@markdown  este é o número máximo de folhas permitidas em uma árvore. Quanto maior o número de folhas, mais complexa será a árvore e mais fácil será para o modelo memorizar os dados de treinamento. No entanto, um número muito grande de folhas pode levar ao overfitting.

#@markdown >  #### Informe o valor de Num_Leaves:
Valor_Num_Leaves = 50 #@param {type:"slider", min:10, max:500, step:10}
#@markdown ---

#@markdown ### Max_Bins :
#@markdown  este é o número máximo de bins (intervalos) que serão usados para discretizar as variáveis contínuas. A discretização ajuda a lidar com valores extremos e a reduzir o impacto de outliers nos dados. Um número maior de bins pode levar a uma melhor precisão, mas também pode levar a overfitting.

#@markdown >  #### Informe o valor de Max_Bins:
Valor_Max_Bins = 250 #@param {type:"slider", min:10, max:500, step:10}
#@markdown ---

#@markdown ### Objective :
#@markdown  é usado para especificar a função de perda que o modelo irá otimizar durante o treinamento. Opções:
#@markdown * binary: Usado para problemas de classificação binária. O modelo tenta otimizar a log-verossimilhança binária.
#@markdown * multiclass: Usado para problemas de classificação multiclasse. O modelo tenta otimizar a log-verossimilhança softmax.
#@markdown * multiclassova:  Usado para problemas de classificação multiclasse. O modelo trata cada classe como um problema de classificação binária e tenta otimizar a log-verossimilhança binária para cada classe.
#@markdown * cross_entropy: Usado para problemas de classificação binária ou multiclasse. O modelo tenta minimizar a entropia cruzada entre as distribuições de probabilidade previstas e as distribuições de probabilidade verdadeiras.
#@markdown * xentropy: Também usado para problemas de classificação binária ou multiclasse, esta opção é semelhante à cross_entropy`, mas usa uma versão mais eficiente do cálculo da entropia cruzada.

#@markdown >  #### Informe o tipo de Objective:
Tipo_Objective = "cross_entropy" #@param ["binary", "multiclass", "multiclassova", "cross_entropy", "xentropy"]
#@markdown ---

#@markdown > * Rode a célula para usar o algoritmo. 

#@markdown > Ao final do processamento você terá acesso aos seguintes resultados:
#@markdown    * Acurácia usando base de treino e teste
#@markdown    * Matriz de Confusão da base de treino e teste
#@markdown    * Relatório de Classificação (precision, recall, f1-score, support)
#@markdown    * Acurácia média usando Validação Cruzada


# Importando biblioteca 
import lightgbm as lgb 

#Evitando a apresentação de mensagens de erro
np.warnings.filterwarnings('ignore')

# Dataset para treino
dataset = lgb.Dataset(x_treino,label=y_treino)

# Parâmetros


# Criando o modelo. 
lgbm = lgb.train(
    {'num_leaves': Valor_Num_Leaves,
     'objective': Tipo_Objective,
     'max_depth': Valor_Max_Depth,
     'learning_rate': Valor_Learning_Rate,
     'max_bin': Valor_Max_Bins
    },
    dataset,
    num_boost_round=Valor_Num_Boost_Round
)

# Criação do PREVISOR da base de teste
previsoes_lgbm = lgbm.predict(x_teste)

# Criando Dataframe para receber dados treino
previsoes_treino = lgbm.predict(x_treino)

# Base de teste: Quando for menor que 5 considera 0 e quando for maior ou igual a 5 considera 1
for i in range(0, len(previsoes_lgbm)):
    if previsoes_lgbm[i] >= 0.5:       
       previsoes_lgbm[i] = 1
    else:  
       previsoes_lgbm[i] = 0

# Base de treino: Quando for menor que 5 considera 0 e quando for maior ou igual a 5 considera 1
for i in range(0, len(previsoes_treino)):
    if previsoes_treino[i] >= 0.5:       
       previsoes_treino[i] = 1
    else:  
       previsoes_treino[i] = 0

print("")

print('\033[1;32mAcurácia da Base de Teste:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_teste, previsoes_lgbm)*100))

print("")

print('\033[1;32mAcurácia da Base de Treino:')
print('\033[0m'+ "%0.2f%%" % (accuracy_score(y_treino, previsoes_treino)*100))

print("")
print(55*"=")
print("")

print('\033[1;32mMatriz de Confusão da Base de Teste:')
print('\033[0m'+ str(confusion_matrix(y_teste, previsoes_lgbm)))

print("")

print('\033[1;32mMatriz de Confusão da Base de Treino:')
print('\033[0m'+ str(confusion_matrix(y_treino, previsoes_treino)))

print("")
print(55*"=")
print("")

print('\033[1;32mRelatório de Classificação da Base de Teste:')
print('\033[0m'+ str(classification_report(y_teste, previsoes_lgbm)))

print('\033[1;32mRelatório de Classificação da Base de Treino:')
print('\033[0m'+ str(classification_report(y_treino, previsoes_treino)))

print("")
print(55*"=")
print("")

# Validação cruzada:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

# Criando o modelo.
modelo_lgbm = lgb.LGBMClassifier(num_leaves = Valor_Num_Leaves, objective = Tipo_Objective,     
                            max_depth = Valor_Max_Depth, learning_rate = Valor_Learning_Rate, max_bin =Valor_Max_Bins)

resultado_lgbm = cross_val_score(modelo_lgbm, previsores_esc,alvo,cv=kfold)

# Usando a média e desvio padrão
print('\033[1;32mAcurácia na Validação Cruzada:')
print('\033[0m'+ str("Acurácia Média: %.2f%%" %(resultado_lgbm.mean()*100)))

print("")
print(55*"=")
print("")

print('\033[1;32mLightGBM Finalizado!')

Processando LightGBM...
[LightGBM] [Info] [cross_entropy:Init]: (objective) labels passed interval [0, 1] check
[LightGBM] [Info] [cross_entropy:Init]: (metric) labels passed interval [0, 1] check
[LightGBM] [Info] [cross_entropy:Init]: sum-of-weights = 4188.000000
[LightGBM] [Warning] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001166 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 395
[LightGBM] [Info] Number of data points in the train set: 4188, number of used features: 43
[LightGBM] [Info] [cross_entropy:BoostFromScore]: pavg = 0.270057 -> initscore = -0.994332
[LightGBM] [Info] Start training from score -0.994332

Acurácia da Base de Teste:
78.73%

Acurácia da Base de Treino:
80.49%


Matriz de Confusão da Base de Teste:
[[1221  119]
 [ 263  193]]

Matriz de Confusão da Base de Treino:
[[2830  227]
 [ 590  541]]


Relatório de Classificação da 

# <font color='#FFA500'> ETAPA 4: Comparando o desempenho dos algoritmos</font>

### <font color='#FFFF00'>Acurácia</font>

In [14]:
#@markdown > ### Compare a Acurácia dos Algoritmos. 
#@markdown  * Acurácia é a métrica que mede a proporção de predições corretas feitas pelo modelo em relação ao total de predições feitas. Em outras palavras, a acurácia indica a porcentagem de vezes que o modelo classificou corretamente as amostras de dados.
#@markdown ### Atenção! 
#@markdown A Acurácia não é a principal métrica de avaliação e deve ser avaliada em conjunto com outras métricas.

# Importando bibliotecas
import plotly.graph_objs as go
#==============================================================
# Atribuindo médias para resultados de acuracia:
Naive_Bayes = (sum(resultado_nbayes) / len(resultado_nbayes)) 
S_V_M = (sum(resultado_svm) / len(resultado_svm)) 
Reg_Logistica = (sum(resultado_rl) / len(resultado_rl)) 
K_N_N = (sum(resultado_knn) / len(resultado_knn)) 
Arv_Decisao = (sum(resultado_ad) / len(resultado_ad)) 
R_Forest = (sum(resultado_rf) / len(resultado_rf)) 
XG_BOOST = (sum(resultado_xgboost) / len(resultado_xgboost)) 
Light_GBM = (sum(resultado_lgbm) / len(resultado_lgbm)) 

# Criando lista com acurácias
acuracia = [Naive_Bayes ,S_V_M, Reg_Logistica, K_N_N, Arv_Decisao, R_Forest, XG_BOOST, Light_GBM]
maior_acuracia = max(acuracia)

# Definindo nomes e cores
nome_algoritmos = ['Naive_Bayes', 'S_V_M', 'Reg_Logistica', 'K_N_N', 'Arv_Decisao', 'R_Forest', 'XG_BOOST', 'Light_GBM']

#cores = ['red' if acuracia[i] == maior_acuracia else 'blue' for i in range(len(acuracia))]
cores = ['blue'] * len(acuracia)
indice_maior_acuracia = acuracia.index(maior_acuracia)
cores[indice_maior_acuracia] = 'red'

# Criando rótulos para as barras com o valor recall e o percentual correspondente
#labels = [f'{acur_perc:.2%}' for nome, acur, acur_perc in zip(nome_algoritmos, acuracia, (acuracia)*100 )]
labels = [f'{acur_perc:.2%}' for nome, acur, acur_perc in zip(nome_algoritmos, acuracia, acuracia)]

# Criando gráfico:
data = [go.Bar(x=nome_algoritmos, y=acuracia, marker=dict(color=cores), text=labels, textposition='auto')]

# Configurando layout:
layout = go.Layout(title='Comparação de Acurácia entre os Algoritmos',
                   xaxis=dict(title='Algoritmos'),
                   yaxis=dict(title='Acurácia'))

fig = go.Figure(data=data, layout=layout)

fig.show()




### <font color='#FFFF00'>Precisão</font>

In [ ]:
#@markdown > ### Avalie a Precisão dos Algoritmos
#@markdown > * Precisão é uma métrica que mede a proporção de verdadeiros positivos (TP) em relação a todos os exemplos classificados como positivos (TP + falsos positivos, FP). Em outras palavras, a precision indica quantos casos previstos corretamente foram positivos. Quanto maior a precision, menor a proporção de exemplos que foram erroneamente classificados como positivos.
#@markdown ### Situações em que Precisão é muito importante:
#@markdown * Detecção de Fraude
#@markdown * Risco
#@markdown * Marketing

# Importando biblioteca:
from numpy import mean

# Validando o Precisão:
Naive_Bayes = mean(cross_val_score(modelo_nbayes,previsores_esc,alvo,cv=kfold, scoring='precision'))
S_V_M = mean(cross_val_score(modelo_svm,previsores_esc,alvo,cv=kfold, scoring='precision'))
Reg_Logistica = mean(cross_val_score(modelo_rl,previsores_esc,alvo,cv=kfold, scoring='precision'))
K_N_N = mean(cross_val_score(modelo_knn,previsores_esc,alvo,cv=kfold, scoring='precision'))
Arv_Decisao = mean(cross_val_score(modelo_ad,previsores_esc,alvo,cv=kfold, scoring='precision'))
R_Forest = mean(cross_val_score(modelo_rf,previsores_esc,alvo,cv=kfold, scoring='precision'))
XG_BOOST = mean(cross_val_score(modelo_xgboost,previsores_esc,alvo,cv=kfold, scoring='precision'))
Light_GBM = mean(cross_val_score(modelo_lgbm,previsores_esc,alvo,cv=kfold, scoring='precision'))


# Criando lista com precision score
lista_precision = [Naive_Bayes ,S_V_M, Reg_Logistica, K_N_N, Arv_Decisao, R_Forest, XG_BOOST, Light_GBM]
maior_precision = max(lista_precision)

# Definindo nomes e cores
nome_algoritmos = ['Naive_Bayes', 'S_V_M', 'Reg_Logistica', 'K_N_N', 'Arv_Decisao', 'R_Forest', 'XG_BOOST', 'Light_GBM']

#cores = ['red' if acuracia[i] == maior_acuracia else 'blue' for i in range(len(acuracia))]
cores = ['blue'] * len(lista_precision)
indice_maior_precision = lista_precision.index(maior_precision)
cores[indice_maior_precision] = 'red'

# Criando rótulos para as barras com o valor precision e o percentual correspondente
labels = [f'{precision_perc:.2%}' for nome, pecision, precision_perc in zip(nome_algoritmos, lista_precision, (lista_precision)*100 )]

# Criando gráfico:
data = [go.Bar(x=nome_algoritmos, y=lista_precision, marker=dict(color=cores),text=labels,textposition='auto')]

# Configurando layout:
layout = go.Layout(title='Comparação de Precisão entre os Algoritmos',
                   xaxis=dict(title='Algoritmos'),
                   yaxis=dict(title='Precisão'))

fig = go.Figure(data=data, layout=layout)

fig.show()


### <font color='#FFFF00'>Recall</font>

In [ ]:
#@markdown > ### Avalie o Recall dos Algoritmos
#@markdown > * Recall é uma métrica que mede a capacidade do modelo em identificar corretamente os verdadeiros positivos, ou seja, quantos exemplos positivos reais conseguimos prever com o modelo. Útil em casos que Falso Negativo supera Falso Positivo.
#@markdown ### Situações em que Precisão é muito importante:
#@markdown * Detecção de fraudes financeiras
#@markdown * Diagnóstico médico, pois um falso negativo pode levar um paciente a morte
#@markdown * Diagnóstico de falhas em equipamentos

# Importando biblioteca:
from numpy import mean

# Validando o Precisão:
Naive_Bayes = mean(cross_val_score(modelo_nbayes,previsores_esc,alvo,cv=kfold, scoring='recall'))
S_V_M = mean(cross_val_score(modelo_svm,previsores_esc,alvo,cv=kfold, scoring='recall'))
Reg_Logistica = mean(cross_val_score(modelo_rl,previsores_esc,alvo,cv=kfold, scoring='recall'))
K_N_N = mean(cross_val_score(modelo_knn,previsores_esc,alvo,cv=kfold, scoring='recall'))
Arv_Decisao = mean(cross_val_score(modelo_ad,previsores_esc,alvo,cv=kfold, scoring='recall'))
R_Forest = mean(cross_val_score(modelo_rf,previsores_esc,alvo,cv=kfold, scoring='recall'))
XG_BOOST = mean(cross_val_score(modelo_xgboost,previsores_esc,alvo,cv=kfold, scoring='recall'))
Light_GBM = mean(cross_val_score(modelo_lgbm,previsores_esc,alvo,cv=kfold, scoring='recall'))

# Criando lista com recall score
lista_recall = [Naive_Bayes ,S_V_M, Reg_Logistica, K_N_N, Arv_Decisao, R_Forest, XG_BOOST, Light_GBM]
maior_recall = max(lista_recall)

# Definindo nomes e cores
nome_algoritmos = ['Naive_Bayes', 'S_V_M', 'Reg_Logistica', 'K_N_N', 'Arv_Decisao', 'R_Forest', 'XG_BOOST', 'Light_GBM']

#cores = ['red' if acuracia[i] == maior_acuracia else 'blue' for i in range(len(acuracia))]
cores = ['blue'] * len(lista_recall)
indice_maior_Recall = lista_recall.index(maior_recall)
cores[indice_maior_Recall] = 'red'

# Criando rótulos para as barras com o valor recall e o percentual correspondente
labels = [f'{recall_perc:.2%}' for nome, recall, recall_perc in zip(nome_algoritmos, lista_recall, (lista_recall)*100 )]

# Criando gráfico:
data = [go.Bar(x=nome_algoritmos, y=lista_recall, marker=dict(color=cores), text=labels, textposition='auto')]

# Configurando layout:
layout = go.Layout(title='Comparação de Recall entre os Algoritmos',
                   xaxis=dict(title='Algoritmos'),
                   yaxis=dict(title='Recall'))

fig = go.Figure(data=data, layout=layout)

fig.show()

### <font color='#FFFF00'>F1-Score</font>

In [ ]:
#@markdown > ### Avalie o F1-Score dos Algoritmos
#@markdown > * O F1-score é uma métrica que combina as métricas de precisão e recall em uma única medida. Ele é útil quando há um desequilíbrio nas classes de dados, onde uma classe é mais frequente do que a outra.

# Importando biblioteca:
from numpy import mean
# Validando o f1
scores_nbayes = cross_val_score(modelo_nbayes,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
Naive_Bayes = mean(scores_nbayes)
scores_svm = cross_val_score(modelo_svm,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
S_V_M = mean(scores_svm)
scores_rl = cross_val_score(modelo_rl,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
Reg_Logistica = mean(scores_rl)
scores_knn = cross_val_score(modelo_knn,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
K_N_N = mean(scores_knn)
scores_ad = cross_val_score(modelo_ad,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
Arv_Decisao = mean(scores_ad)
scores_rf = cross_val_score(modelo_rf,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
R_Forest = mean(scores_rf)
scores_xgboost = cross_val_score(modelo_xgboost,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
XG_BOOST = mean(scores_xgboost)
scores_lgbm = cross_val_score(modelo_lgbm,previsores_esc,alvo,cv=kfold, scoring='f1_macro')
Light_GBM = mean(scores_lgbm)

# Criando lista com f1 score
lista_f1 = [Naive_Bayes ,S_V_M, Reg_Logistica, K_N_N, Arv_Decisao, R_Forest, XG_BOOST, Light_GBM]
maior_f1 = max(lista_f1)

# Definindo nomes e cores
nome_algoritmos = ['Naive_Bayes', 'S_V_M', 'Reg_Logistica', 'K_N_N', 'Arv_Decisao', 'R_Forest', 'XG_BOOST', 'Light_GBM']

#cores = ['red' if acuracia[i] == maior_acuracia else 'blue' for i in range(len(acuracia))]
cores = ['blue'] * len(lista_f1)
indice_maior_f1 = lista_f1.index(maior_f1)
cores[indice_maior_f1] = 'red'

# Criando rótulos para as barras com o valor F1 e o percentual correspondente
labels = [f'{f1_perc:.2%}' for nome, f1, f1_perc in zip(nome_algoritmos, lista_f1,(lista_f1) *100 )]

# Criando gráfico:
data = [go.Bar(x=nome_algoritmos, y=lista_f1, marker=dict(color=cores), text=labels, textposition='auto')]

# Configurando layout:
layout = go.Layout(title='Comparação de F1 Score entre os Algoritmos',
                   xaxis=dict(title='Algoritmos'),
                   yaxis=dict(title='F1 Score'))

fig = go.Figure(data=data, layout=layout)

fig.show()


### <font color='#FFFF00'>Falsos Positivos</font> - Erro Tipo I

In [ ]:
#@markdown > ### Avalie Falsos Positivos dos Algoritmos
#@markdown > * Falsos positivos ocorrem quando um classificador prevê incorretamente que uma entrada pertence a uma determinada classe, quando na verdade não pertence, gerando um Erro do Tipo 1.

#@markdown > Os falsos positivos podem ser problemáticos em muitos contextos. Por exemplo, em diagnósticos médicos, um falso positivo pode levar a um tratamento desnecessário e caro, além de causar estresse e ansiedade desnecessários para o paciente. Em segurança cibernética, um falso positivo pode levar a uma interrupção desnecessária nos sistemas e à perda de tempo e recursos da equipe de segurança.

#@markdown #### IMPORTANTE: considere o algoritmo com menor taxa de Falsos Positivos

# Importando biblioteca:
from sklearn.model_selection import cross_val_predict

# Validando o FP
N_Bayes_Predict = cross_val_predict(modelo_nbayes,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, N_Bayes_Predict).ravel()
Naive_Bayes = fp / (fp + tn)

SVM_Predict = cross_val_predict(modelo_svm,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, SVM_Predict).ravel()
S_V_M = fp / (fp + tn)

RL_Predict = cross_val_predict(modelo_rl,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, RL_Predict).ravel()
Reg_Logistica = fp / (fp + tn)

KNN_Predict = cross_val_predict(modelo_knn,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, KNN_Predict).ravel()
K_N_N = fp / (fp + tn)

AD_Predict = cross_val_predict(modelo_ad,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, AD_Predict).ravel()
Arv_Decisao = fp / (fp + tn)

RF_Predict = cross_val_predict(modelo_rf,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, RF_Predict).ravel() 
R_Forest = fp / (fp + tn)

XG_Predict = cross_val_predict(modelo_xgboost,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, XG_Predict).ravel()
XG_BOOST = fp / (fp + tn)

LGBM_Predict = cross_val_predict(modelo_lgbm,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, LGBM_Predict).ravel()
Light_GBM = fp / (fp + tn)


# Criando lista com fp 
lista_fp = [Naive_Bayes ,S_V_M, Reg_Logistica, K_N_N, Arv_Decisao, R_Forest, XG_BOOST, Light_GBM]
menor_fp = min(lista_fp)

# Definindo nomes e cores
nome_algoritmos = ['Naive_Bayes', 'S_V_M', 'Reg_Logistica', 'K_N_N', 'Arv_Decisao', 'R_Forest', 'XG_BOOST', 'Light_GBM']

cores = ['blue'] * len(lista_fp)
indice_menor_fp = lista_fp.index(menor_fp)
cores[indice_menor_fp] = 'red'

# Criando rótulos para as barras com o valor FP e o percentual correspondente
labels = [f'{fp_perc:.2%}' for nome, fp, fp_perc in zip(nome_algoritmos, lista_fp,(lista_fp)*100 )]

# Criando gráfico:
data = [go.Bar(x=nome_algoritmos, y=lista_fp, marker=dict(color=cores), text=labels, textposition='auto')]

# Configurando layout:
layout = go.Layout(title='Comparação de Falsos Positivos entre os Algoritmos',
                   xaxis=dict(title='Algoritmos'),
                   yaxis=dict(title='Falsos Positivos'))

fig = go.Figure(data=data, layout=layout)

fig.show()

### <font color='#FFFF00'>Falsos Negativos</font> - Erro Tipo II

In [ ]:
#@markdown > ### Avalie Falsos Negativos dos Algoritmos
#@markdown > * Falsos negativos ocorrem em avaliações de classificadores quando uma amostra é erroneamente classificada como negativa quando, na verdade, ela deveria ter sido classificada como positiva. Em outras palavras, o classificador falha em detectar uma condição ou evento que deveria ser considerado positivo, gerando um Erro do Tipo II.

#@markdown > Por exemplo, em um teste de detecção de câncer, um falso negativo ocorre quando um paciente que realmente tem câncer é diagnosticado como não tendo a doença. Isso pode levar a um atraso no tratamento ou até mesmo à morte.

#@markdown #### IMPORTANTE: considere o algoritmo com menor taxa de Falsos Negativos.

# Importando biblioteca:
from sklearn.model_selection import cross_val_predict

# Validando o fn
N_Bayes_Predict = cross_val_predict(modelo_nbayes,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, N_Bayes_Predict).ravel()
Naive_Bayes = fn / (fn + tp)

SVM_Predict = cross_val_predict(modelo_svm,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, SVM_Predict).ravel()
S_V_M = fn / (fn + tp)

RL_Predict = cross_val_predict(modelo_rl,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, RL_Predict).ravel()
Reg_Logistica = fn / (fn + tp)

KNN_Predict = cross_val_predict(modelo_knn,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, KNN_Predict).ravel()
K_N_N = fn / (fn + tp)

AD_Predict = cross_val_predict(modelo_ad,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, AD_Predict).ravel()
Arv_Decisao = fn / (fn + tp)

RF_Predict = cross_val_predict(modelo_rf,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, RF_Predict).ravel() 
R_Forest = fn / (fn + tp)

XG_Predict = cross_val_predict(modelo_xgboost,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, XG_Predict).ravel()
XG_BOOST = fn / (fn + tp)

LGBM_Predict = cross_val_predict(modelo_lgbm,previsores_esc,alvo,cv=kfold)
tn, fp, fn, tp = confusion_matrix(alvo, LGBM_Predict).ravel()
Light_GBM = fn / (fn + tp)


# Criando lista com fn 
lista_fn = [Naive_Bayes ,S_V_M, Reg_Logistica, K_N_N, Arv_Decisao, R_Forest, XG_BOOST, Light_GBM]
menor_fn = min(lista_fn)

# Definindo nomes e cores
nome_algoritmos = ['Naive_Bayes', 'S_V_M', 'Reg_Logistica', 'K_N_N', 'Arv_Decisao', 'R_Forest', 'XG_BOOST', 'Light_GBM']

cores = ['blue'] * len(lista_fn)
indice_menor_fn = lista_fn.index(menor_fn)
cores[indice_menor_fn] = 'red'

# Criando rótulos para as barras com o valor fn e o percentual correspondente
labels = [f'{fn_perc:.2%}' for nome, fn, fn_perc in zip(nome_algoritmos, lista_fn,(lista_fn)*100 )]

# Criando gráfico:
data = [go.Bar(x=nome_algoritmos, y=lista_fn, marker=dict(color=cores), text=labels, textposition='auto')]

# Configurando layout:
layout = go.Layout(title='Comparação de Falsos Negativos entre os Algoritmos',
                   xaxis=dict(title='Algoritmos'),
                   yaxis=dict(title='Falsos Negativos'))

fig = go.Figure(data=data, layout=layout)

fig.show()